### ISSUE TITLE
Different tile coordinate system in Documenation and bel files

### ISSUE THREAD

**Issue by IAmMarcelJung** [FPGA-Research-Manchester/FABulous#143]
In the [Documentation](https://fabulous.readthedocs.io/en/latest/fabric_definition.html#fabric-csv-description), the tile coordinate system has its origin in the **top** left corner: 
![image](https://github.com/FPGA-Research-Manchester/FABulous/assets/132259776/0a18d99f-5e8a-40a1-8793-bd5328b36bfb)

However, in the bel files (both bel.txt and belv2.txt), the first line states that it is in the **bottom** left corner:
```# BEL descriptions: bottom left corner Tile_X0Y0, top right Tile_X10Y16```

Which one is the correct layout? Or am I getting something wrong? Thanks in advance for any kind of help!

**Comment by TaoBi22** [comment]
Hi @IAmMarcelJung,

IIRC, this was because of a discrepancy between the coordinate systems used internally within FABulous and within nextpnr - you can see a relic of having to convert between the two systems [here](https://github.com/FPGA-Research-Manchester/FABulous/blob/f15a0eb5e0553e0b3a02e49290b2655127bde115/fabric_generator/utilities.py#L830C15-L830C49). I just had a look, and it looks like these days the bel representation also starts at the top-left corner, so this comment is now out-of-date. Thanks for catching that, I'll get it fixed!
